;; (define-key global-map "\C-h" 'delete-backward-char)
(global-set-key "\C-h" 'backward-delete-char-untabify)
(global-set-key "\C-z" 'undo)
;; (global-set-key "\M-?" 'goto-line)
;; (global-set-key [f1] 'help-for-help)
;; (global-set-key [f3] 'isearch-repeat-forward)
;; (global-set-key [f5] 'indent-region)
;; (global-set-key [f6] 'align)
;; (global-set-key [f7] 'comment-region)
;; (global-set-key [f8] 'toggle-truncate-lines)
;; (global-set-key [f9] 'tags-apropos)
;; (global-set-key [f10] 'next-error)
;;(global-set-key [f11] 'speedbar)
;; (global-set-key [f12] 'find-tag)
;; (global-set-key [mouse-2] 'mouse-set-point)
